# Test configuration values
service:
  type: ClusterIP
  port: 8080

deployment:
  replicas: 1
  image:
    repository: test/app
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

config:
  logLevel: debug
  environment: test
